### ISSUE TITLE
Предложение по развитию

### ISSUE THREAD

**Issue by PalachMB** [stanislavvv/fb2_srv_pseudostatic#1]
Было бы интересно добавить на главную страницу количество книг в библиотеке (ну как без piskomerki) и простейшую авторизацию для доступа. Чтобы не светить так открыто наружу. Ну и может быть что-то на несколько пользователей, чтобы реализовать использование "книжной полки" с прочитанным.
На текущий момент решил вопрос доступа через настройку nginx
```
auth_basic "Access denied";
auth_basic_user_file /var/www/html/pass;
```
Ну, и если возможно, конвертер формата книги для всяческих киндлов. В тот же epub.
С автозапуском при старте сервера особо не заморачивался, оформил через запуск rc.local
cat rc.local
```
#!/bin/sh -e
sh /usr/sbin/biblioteka &
exit 0
```
cat /usr/sbin/biblioteka
```
#!/bin/sh
screen -d -m -S fb2_service sh
cd /data/sites/library/fb2_srv_pseudostatic
su -c 'python3 /data/sites/library/fb2_srv_pseudostatic/opds.py' palachmb
```
Криво, косо, но - работает

**Comment by stanislavvv** [comment]
Вообще-то не расчитывал, что библиотека будет выставляться без nginx перед приложением, поэтому простейшую авторизацию добавлять смысла нет, вебсервер умеет её лучше, чем я. А для книжной полки требуется полноценная база (не sqlite, как в предыдущем проекте) и т.п., что не потянет микрокомп, на котором всё это у меня крутится. В принципе, запишу в ToDo, но не факт, что это будет быстро.

По поводу запуска — запускаю через runit при помощи gunicorn, сейчас запищу в ToDo на досуге сделать юнит systemd. 

Собственно запуск gunicorn (кусок скрипта):

```shell
BIND="0.0.0.0:8000"
gunicorn3 -e FLASK_ENV=prod --bind="${BIND}" --workers=4 'app:create_app()' --access-logfile -                                                                            
```

**Comment by stanislavvv** [comment]
По конвертерам - посмотрю, но пока маловероятно, что займусь.

**Comment by stanislavvv** [comment]
Понаписал отдельных задач по описанному. Данную глобальную закрываю.
