### ISSUE TITLE
Some trouble after system update

### ISSUE THREAD

**Issue by PalachMB** [stanislavvv/fb2_srv_pseudostatic#5]
Problem with download fb2.books after update to release Debian Bookworm (stable).

Page show error:
`TypeError: send_file() got an unexpected keyword argument 'attachment_filename'`
but for 'read online' file open successful

FIX: 
in file
`fb2_srv_pseudostatic/app/views_dl.py `
on string
`return send_file(memory_file, attachment_filename=zip_name, as_attachment=True)`
change 
`attachment_filename` to `download_name`

[more about ](https://github.com/pallets/flask/issues/4753#issuecomment-1208406305)

**Comment by stanislavvv** [comment]
Thank you. Will add `requirements.txt` for this repo with right versions soon.
This repo is stalled, because i use real database now.
You may try server from https://github.com/stanislavvv/fb2_srv_pg (with this bug at now, but will be fixed).

**Comment by stanislavvv** [comment]
add requirements.txt in 3962bd7

**Comment by stanislavvv** [comment]
Close. No more real development in *pseudostatic.
